# This workflow will build and test a .NET project inside a Docker container

name: .NET with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Step 1: Build the Docker image
    - name: Build Docker Image
      run: |
        docker build -t aspnetwithelk:latest -f src/Dockerfile .

    # Step 2: Run the container and test the application
    - name: Run Tests in Docker Container
      run: |
        docker run --rm aspnetwithelk:latest dotnet test --verbosity normal

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t aspnetwithelk:latest -f src/Dockerfile .
      
    - name: Push Docker Image to Docker Hub
      run: |
        docker tag aspnetwithelk:latest your-dockerhub-username/aspnetwithelk:latest
        docker push your-dockerhub-username/aspnetwithelk:latest